### ISSUE TITLE
Unwanted behaviour for `adb` and `scrcpy` completions.

### ISSUE THREAD

**Issue by mrplumber** [vladimir-kotikov/clink-completions#159] opened 2022-11-07 19:31 UTC
When I open new CMD window and as soon as I type `adb` or `scrcpy` _adb.exe_ process starts before I even press ENTER.
IMO actual command should be called only after a user presses ENTER.

Windows 10 LTSB 2019
clink 1.4.0
clink-completions 0.4.1

**Comment by chrisant996** [comment] 2022-11-07 22:02
Yes, of course. It's running e.g. `adb devices` to produce completions and suggestions.

If you don't want the auto suggestions while typing then you could run off the `clink set auto-suggest.enable false`>

**Comment by mrplumber** [comment] 2022-11-07 23:50
OK, I understand now. Thanks for explanation.

**Comment by chrisant996** [comment] 2022-11-08 00:17
@mrplumber Also ... is there a problem caused by running `adb devices` in the background, or did you just notice in Task Manager (or etc) that it had launched in the background?

If launching it in the background is causing some problem, then please share info about what's happening, so that it can be addressed.

**Comment by mrplumber** [comment] 2022-11-08 11:25
I started looking into it because there is a noticeable freeze after I type last letter of the command (`adb` or `srccpy`) and that last letter is actually displayed (as I indicated earlier, this happens first time I type one of those commands in newly opened CMD window). It turned out console was waiting for the _adb.exe_ process to start in the background. The freeze is little bit annoying and inconvenient although now when I know the rationale behind this I can live with it.

**Comment by chrisant996** [comment] 2022-11-08 16:15
> I started looking into it because there is a noticeable freeze after I type last letter of the command (`adb` or `scrcpy`) and that last letter is actually displayed (as I indicated earlier, this happens first time I type one of those commands in newly opened CMD window). It turned out console was waiting for the _adb.exe_ process to start in the background. The freeze is little bit annoying and inconvenient although now when I know the rationale behind this I can live with it.

@mrplumber I see.  Thanks for describing the problem.  I'm not ok with that behavior happening.  🙂

Let me confirm something:

You're saying you type `ad` and the letters show up, and then you type `b` but there is a delay before the letter shows up, and during the delay an `adb.exe` process launches?

Three things seem wrong about that:
1. Neither suggestions nor completions should be launching `adb` until you press a space.
2. The letter should be displayed before any potential delay could occur.
3. The `adb` process should be launched from a background thread; there shouldn't be a delay in the first place.

So, something unexpected is happening, and I'm glad I asked for more info.

Can you share the full output from `clink set`?  I need to check some settings.  And I'll match your settings and try to reproduce the issue with a debugger attached.

**Comment by chrisant996** [comment] 2022-11-08 17:05
@mrplumber Oh. I see the problem. The `adb.lua` and `scrcpy.lua` argmatchers are written incorrectly.

It uses the wrong argmatcher syntax, and as a result it accidentally runs functions to generate completions at the moment the adb or scrcpy argmatchers are loaded.  Which happens when you press the `b` and it notices there is a `completions\adb.lua` argmatcher script ready to be loaded.

When the correct argmatcher syntax is used, then the completion generator functions only run when completions are requested.  This is totally my mistake, introduced while I was extending the original contributed adb and scrcpy argmatchers.

Fortunately the fix is quick and simple, and I've pushed the fix to the repo.  I'll also publish a new release in the next few days.

Thank you for reporting this!!

**Closed by chrisant996** 2022-11-08 17:05 UTC
Labels: question
