### ISSUE TITLE
Tab completion for git doesn't work on paths/files?

### ISSUE THREAD

**Issue by eggbean** [vladimir-kotikov/clink-completions#190] opened 2024-10-21 02:33 UTC
For quite a while with git, tab completion doesn't seem to work on paths/files. I think this may have been going on for a few weeks, but I wanted to make sure there wasn't anything wrong with my setup before making an issue about it. I don't think there's anything wrong with my setup and this only seems to be happening with git.

**Comment by chrisant996** [comment] 2024-10-21 04:26
Please be more specific about which commands.

**Comment by chrisant996** [comment] 2024-10-28 23:47
@eggbean can you clarify?

**Comment by eggbean** [comment] 2024-10-29 00:46
Hi, sorry, I meant to determine exactly wasn't working before replying...

But I am experiencing pretty much what I already described.

eg.
```
> ls
test.png  test.ps1  test.txt

git add te <Tab> # No completion of the filename
git checkout te <Tab> # No completion of the filename
git checkout te <Tab> # No completion of the filename

# git restore does complete
# git diff does complete
# git log does complete

# It does complete when the path begins with a dot
git add .\te <Tab> > test.txt completes
git add ./te <Tab> > test.txt completes
git add ..\testdir\tes <Tab> > test.txt completes.
```
Completion of git commands and arguments work fine.

So git add and checkout don't work and probably others too.

**Comment by chrisant996** [comment] 2024-10-29 01:22
> ```inputrc
> "\t":  "luafunc:fzf_complete"
> ```
>
> Does the second line make the first redundant?

@eggbean Yes, the second `"\t"` binding supersedes the first one.

I can't reproduce the issue.  For me, both `old-menu-complete` and `"luafunc:fzf_complete"` are able to complete `te` without any problems, regardless whether the cwd is the repo root or a subdirectory beneath the root.

Are you trying to `git add` a file that doesn't have any working deltas?  The completions are smart and `git add` only includes untracked files and modified files, and `git checkout` only includes tracked modified files.  That behavior was introduced in the clink-completions repo more than 2 years ago.

The reason inserting `.\` works because that forces using file system completions instead of `git status`-based completions.

Can you try updating to the latest clink-completions and also the latest clink-fzf (or clink-gizmos, depending on which one you're using)?

If that doesn't help, then please share more info:
- What version of clink-completions are you using?  (Or what is your HEAD hash?)
- What version of clink-fzf or clink-gizmos are you using, i.e. what is your HEAD hash?
- What version of clink are you using?
- What is the output from `clink set`?
- What is the repo root?
- What is the current working directory?
- When you encounter the completion problem, what is the output from `git status -uno`, and what is the output from `git status -uall`?

**Comment by chrisant996** [comment] 2024-11-07 05:15
@eggbean Gentle reminder -- there's nothing I can do until more information is available. In the meantime, I'm closing this issue since it isn't actionable at this time.

**Closed** 2024-11-07 05:15 UTC
Labels: needs more information
